---
- name: Install packages
  hosts: all

  tasks: 
    - name: install openscap and openscap scanner
      yum:
        name:
          - openscap
          - openscap-scanner
          - scap-security-guide
        state: latest      
