---
- name: Install packages
  hosts: all

  tasks: 
    - name: install openscap and openscap scanner
      yum:
        name:
          - openscap
          - openscap-scanner
        state: latest
        
    - name: install openscap security guide
      yum:
        name: scap-security-guide-0.1.54-5.el8
        allow_downgrade: yes
        
